# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1f9cb763662d795798d4a921e1c3e5c319730bbede10c877dd17b88b9f2ab3dfd7d5a2c6fff8594118517aaddc16effb9fb08e3f394871fc45d674e87fae515b

test:
  secret_key_base: d929dbaf763e4bc9f6af6e1fc2ae7eeee433ed5f13623647d019fb1e60f6bc53bee6cf2a714a6db1b605f58c1d6b6f75185b6caa2906a649cf7a0a664b64992a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
